name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: SVa9OzCvqedk88cSlhIGfA6n
  VERCEL_PROJECT_ID: prj_fnNLY1F7ItcTZBNxX12TJEYEQOHL
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=1hujFasFp2qEv6ma9mnyZQy8
      - name: Build Project Artifacts
        run: vercel build --token=1hujFasFp2qEv6ma9mnyZQy8
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=1hujFasFp2qEv6ma9mnyZQy8
